export const KEY="seqchip-demo-v1";
export const TODAY="2026-09-22";
export const PARTS=[{id:"SC6820",name:"电源管理芯片",pkg:"QFN32"},{id:"SC3215",name:"音频功放",pkg:"QFN24"},{id:"SC9102",name:"传感驱动 · 新品",pkg:"WLCSP"}];
export function seed(){return {revision:1,afternoon:false,wipUpdated:false,ftReply:null,ftReconfirmed:false,assemblyReply:null,assemblyReconfirmed:false,evidence:{},priority:"none",shipped:false,received:false,release:false,waferPlan:false,assessment:null,taskFilter:"all",owner:"all",view:"today",lotFilter:"all",lotSearch:"",selectedPart:"SC6820",guideStep:0,events:[{time:"09:05",title:"销售提出新交期询问",detail:"星河终端需要 SC6820 100,000 颗，要求 9 月 25 日到货。",kind:"request"},{time:"08:40",title:"库存与订单快照已就绪",detail:"BI 库存、OA 订单样例已关联；工厂最新 WIP 等待更新。",kind:"source"}],messages:[]};}
export function lots(s){return [
{id:"FG-0921",part:"SC6820",factory:"中心仓",stage:"成品库存",stageIndex:4,quantity:30000,reserved:10000,basis:"实测良品",eta:"2026-09-23",status:"released",source:"BI 库存样例 · 08:40",note:"已扣除晨光数码订单预留 10,000 颗"},
{id:"FT-0920",part:"SC6820",factory:"启明测试",stage:"待终测",stageIndex:3,quantity:50000,reserved:0,basis:"预计良品",eta:s.ftReply==="rejected"?"2026-09-28":"2026-09-25",status:s.ftReply==="accepted"?"confirmed":"conditional",source:s.ftReply?"工厂反馈样例 · "+(s.evidence?.ft?.time||"09:30"):"WIP 样例 · "+(s.wipUpdated?"09:20":"昨日 17:00"),note:s.ftReply==="accepted"?(s.afternoon&&!s.ftReconfirmed?"确认已到复核时点；尚无实际开测证据":"工厂确认 9/23 开测；最终良品与放行待验证"):s.ftReply==="rejected"?"工厂反馈测试档期不足，预计 9/28 到货":"测试档期未确认，预计 9/25 到货"},
{id:"AS-0917",part:"SC6820",factory:"华成封装",stage:"封装中",stageIndex:2,quantity:30000,reserved:0,basis:"预计良品",eta:s.priority==="accepted"&&s.assemblyReply!=="rejected"?"2026-09-25":"2026-09-29",status:s.priority==="accepted"?"confirmed":"processing",source:"WIP 样例 · "+(s.wipUpdated?"09:20":"昨日 17:00"),note:s.priority==="accepted"?(s.afternoon&&!s.assemblyReconfirmed?"加急优先级到期需复核":"工厂已接受加急；尚未实际完工"):"正常排程 9/29 到货，不能覆盖 9/25 需求"},
{id:"WF-0905",part:"SC6820",factory:"远景晶圆",stage:"晶圆在制",stageIndex:0,quantity:72000,reserved:0,basis:"预计成品良品",eta:"2026-10-13",status:"processing",source:"晶圆周报样例 · 9/21",note:"12 片晶圆折算预计成品 72,000 颗；后续周期及良率为样例参数"},
{id:"FT-0918",part:"SC3215",factory:"启明测试",stage:s.received?"客户已收货":s.shipped?"客户在途":"待直发",stageIndex:4,quantity:8000,reserved:8000,basis:"实测良品",eta:"2026-09-24",status:s.received?"received":s.shipped?"shipped":"released",source:"质量放行样例 · 09:00",note:"已分配给青禾智能订单；可由测试厂直发"},
{id:"AS-0919",part:"SC3215",factory:"华成封装",stage:"封装中",stageIndex:2,quantity:20000,reserved:20000,basis:"预计良品",eta:s.priority==="accepted"?"2026-09-28":"2026-09-25",status:s.priority==="accepted"?"risk":"processing",source:"排产计划样例 · 9/21",note:s.priority==="accepted"?"受 SC6820 加急挤占，较原计划延期 3 天":"已分配北辰电子订单，与 AS-0917 共享封装资源"},
{id:"NP-0922",part:"SC9102",factory:"启明测试",stage:s.release?"待测试排期":"待发料",stageIndex:s.release?3:1,quantity:5000,reserved:5000,basis:"预计良品",eta:"2026-09-28",status:"conditional",source:"新品投料计划样例 · 9/21",note:s.release?"加工单已受理；发料交接已登记，未实际开测":"新品小批 5,000 颗，测试程序已准备；待发料与加工受理"}
];}
export function assess(s,part,quantity,date){if(!PARTS.some(p=>p.id===part))throw Error("请选择演示中的型号");if(!Number.isInteger(quantity)||quantity<=0||quantity>10000000)throw Error("数量需为 1–10,000,000 的整数");if(!/^2026-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date||date<TODAY)throw Error("请选择演示日 2026-09-22 或之后的有效到货日期");let remaining=quantity,stock=0,expected=0;const rows=lots(s).filter(l=>l.part===part&&l.status!=="shipped"&&l.status!=="received").map(l=>({...l,available:Math.max(0,l.quantity-l.reserved)})).filter(l=>l.available>0).sort((a,b)=>a.eta.localeCompare(b.eta)||a.stageIndex-b.stageIndex);const selected=rows.map(l=>{const use=l.eta<=date?Math.min(l.available,remaining):0;remaining-=use;if(l.stage==="成品库存")stock+=use;else expected+=use;return {...l,use,onTime:l.eta<=date};});const conditions=[];if(!s.wipUpdated&&selected.some(l=>l.use>0&&l.stage!=="成品库存"))conditions.push("封测 WIP 尚为昨日快照，需要更新后复核");if(selected.some(l=>l.id==="FT-0920"&&l.use>0)){if(s.ftReply!=="accepted")conditions.push("FT-0920 测试档期待工厂确认");else if(s.afternoon&&!s.ftReconfirmed)conditions.push("FT-0920 旧确认已到复核时点");conditions.push("FT-0920 最终良品数量及质量放行待验证");}if(selected.some(l=>l.id==="AS-0917"&&l.use>0)){if(s.priority!=="accepted")conditions.push("AS-0917 后续加工、测试及运输排期待确认");else if(s.afternoon&&!s.assemblyReconfirmed)conditions.push("AS-0917 加急优先级需再次复核");conditions.push("AS-0917 预计良品数量和完工时间待验证");}if(selected.some(l=>l.id==="WF-0905"&&l.use>0))conditions.push("晶圆供给按剩余良率与路线周期折算，需确认晶圆及封测档期");if(expected>0&&conditions.length===0)conditions.push("在制供给需验证完工、最终良品和质量放行");return {part,quantity,date,stock,expected,gap:remaining,rows:selected,conditions,revision:s.revision,status:remaining>0?"gap":expected>0?"conditional":"covered",createdAt:s.afternoon?"15:00":"09:30"};}
export function tasks(s){return [
{id:"wip",title:"处理两家封测厂晨间 WIP",type:"慢线 · 每日上午",owner:"陈悦",part:"全部型号",due:"09:30",priority:"routine",status:s.wipUpdated?"done":"todo",description:"核对批次、数量和站点变化，识别缺报与停滞。",action:"更新 WIP"},
{id:"delivery",title:"SC6820 · 10 万颗交期答复",type:"快线 · 销售询期",owner:"陈悦",part:"SC6820",due:"10:30",priority:"urgent",status:s.assessment?"review":"todo",description:"星河终端要求 9/25 到货，允许分批交付。",action:"测算交期"},
{id:"ft",title:s.afternoon&&!s.ftReconfirmed&&s.ftReply==="accepted"?"复核 FT-0920 测试优先级":"确认 FT-0920 测试档期",type:"快线 · 工厂确认",owner:"林浩",part:"SC6820",due:s.afternoon?"15:00":"11:00",priority:"urgent",status:s.ftReply==="accepted"&&(!s.afternoon||s.ftReconfirmed)?"done":s.ftReply==="rejected"?"review":"waiting",description:"确认 5 万颗的开测时间、预计出厂及到货时间。",action:"记录工厂反馈"},
...(s.priority!=="none"?[{id:"priority",title:s.afternoon&&!s.assemblyReconfirmed?"复核 AS-0917 加急优先级":"确认 AS-0917 加急排程",type:"快线 · 急件协调",owner:"林浩",part:"SC6820",due:s.afternoon?"15:00":"11:30",priority:"urgent",status:s.priority==="accepted"&&(!s.afternoon||s.assemblyReconfirmed)?"done":s.priority==="rejected"?"review":"waiting",description:"计划目标 9/25 到货；共享资源会影响北辰电子订单。",action:"记录工厂反馈"}]:[]),
...(s.ftReply==="accepted"?[{id:"fttrack",title:"跟进 FT-0920 实际开测",type:"快线 · 进度跟踪",owner:"林浩",part:"SC6820",due:"9/23",priority:"routine",status:"waiting",description:"已取得工厂档期确认；仍需实际进站或开测证据。",action:"查看跟进"}]:[]),
...(s.priority==="accepted"?[{id:"impact",title:"北辰电子 · 加急挤占风险答复",type:"快线 · 订单影响",owner:"陈悦",part:"SC3215",due:"16:00",priority:"urgent",status:"review",description:"20,000 颗预计从 9/25 推迟到 9/28，尚未获得客户接受。",action:"查看影响"}]:[]),
{id:"npi",title:"SC9102 新品 · 发料与测试下单",type:"慢线 · 投料",owner:"周宁",part:"SC9102",due:"11:30",priority:"routine",status:s.release?"done":"todo",description:"试产 5,000 颗，核对路线与测试程序，登记发料和加工受理。",action:"查看投料"},
{id:"ship",title:s.shipped?"核对青禾智能直发收货":"SC3215 · 8,000 颗工厂直发",type:"慢线 · 回货与交付",owner:"王蕾",part:"SC3215",due:s.shipped?"9/24":"14:00",priority:"routine",status:s.received?"done":s.shipped?"waiting":"todo",description:s.shipped?"货物已交承运方，实际签收待核对。":"终测已完成且质量放行，按客户订单安排直发。",action:s.shipped?"核对收货":"安排直发"},
{id:"wafer",title:"准备 10 月 5 日晶圆采购建议",type:"慢线 · 每月两次",owner:"赵宇",part:"SC6820",due:"10/05",priority:"routine",status:s.waferPlan?"done":"todo",description:"核对净预测与 10 月供给缺口，形成建议；本月 5 日、20 日已执行。",action:"查看采购建议"}
];}
export const format=n=>new Intl.NumberFormat("zh-CN").format(n);
export const short=n=>n>=10000?(n/10000).toFixed(n%10000?1:0)+" 万":format(n);
