let data,view='today',busy=false;
const $=s=>document.querySelector(s),esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>new Intl.NumberFormat('zh-CN').format(v||0);const badge=(text,kind='')=>`<span class="badge ${kind}">${esc(text)}</span>`;
const pages={today:'今日运营总览',wip:'全链路 WIP',orders:'订单与交付',issues:'异常协同',production:'投料与回货',agent:'Agent 运行中心',data:'数据与业务口径'};
const name=(type,id)=>data.state[type].find(x=>x.id===id)?.name||id||'未归因';
const time=v=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—';
const button=(text,action,extra='')=>`<button data-action="${action}" ${extra}>${text}</button>`;
function notify(text,error=false){$('#notice').innerHTML=`<div class="notice ${error?'error':''}">${esc(text)}</div>`;}
async function load(){const r=await fetch('/api/state');const d=await r.json();if(!r.ok)throw Error(d.error);data=d;render();}
async function run(command,key=crypto.randomUUID()){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,command})});const d=await r.json();if(!r.ok)throw Error(d.error);await load();notify(d.duplicate?'已识别重复操作，未重复记账。':'台账已更新，供需与异常已重新计算。');return d;}catch(e){notify(e.message,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function shell(){ $('#nav').innerHTML=Object.entries(pages).map(([k,v])=>`<button data-view="${k}" class="${view===k?'active':''}">${v}</button>`).join('');$('#title').textContent=pages[view];$('#clock').textContent=`模拟业务时钟 ${time(data.state.clock)} · 版本 ${data.revision}`; }
function today(){const s=data.state,p=data.plan,open=s.issues.filter(x=>x.status!=='resolved');return `<div class="kpis"><div class="kpi"><span>活跃批次</span><strong>${p.lots.filter(l=>!['closed','shipped'].includes(l.status)).length}</strong><small>按工序与来源追踪</small></div><div class="kpi warn"><span>交付风险订单</span><strong>${p.orders.filter(o=>o.gap>0).length}<small>共 ${p.orders.length} 笔未结订单</small></strong></div><div class="kpi"><span>未交余额 · 颗</span><strong>${n(p.orders.reduce((a,o)=>a+o.open,0))}</strong><small>已扣实际出货</small></div><div class="kpi warn"><span>待跟进异常</span><strong>${open.length}</strong><small>保留每次反馈与复核时间</small></div></div><div class="grid"><section class="panel"><div class="panel-head"><h2>今天该协调什么</h2>${badge('按当前证据推导','good')}</div>${open.slice(0,6).map(x=>`<div class="row-card"><div class="top"><strong>${esc(x.subject)}</strong>${badge(x.kind,'warn')}</div><p>${esc(x.reason)}</p><small>${esc(x.nextAction)} · ${esc(x.owner)}</small>${button('查看并跟进','issue',`data-id="${esc(x.id)}"`)}</div>`).join('')||'<p>暂无待跟进异常</p>'}</section><section><div class="panel"><h2>数据接入状态</h2>${s.sources.map(x=>`<div class="row-card"><div class="top"><strong>${esc(x.name)}</strong>${badge(x.connector)}</div><small>源时间 ${time(x.observedAt)}</small></div>`).join('')}</div><div class="panel"><h2>业务闭环演示</h2><p class="muted">先模拟测试延期，再比较加急影响，最后登记回货与交付。</p><div class="actions" style="margin-top:16px">${button('① 测试批次延期','delay')}${button('② 比较加急方案','expedite')}${button('③ 回货与出货','production')}</div></div></section></div>`;}
let filters={query:'',factory:'',stage:'',pn:'',project:'',order:''};
const activeLots=()=>data.plan.lots.filter(l=>!['closed','shipped'].includes(l.status));
const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
function options(values,selected){return '<option value="">全部</option>'+[...new Set(values)].filter(Boolean).map(x=>`<option value="${esc(x)}" ${selected===x?'selected':''}>${esc(x)}</option>`).join('');}
function wip(){
 const lots=activeLots();const stages=['晶圆制造','晶圆测试','Die 库存','封装','成品测试','成品库存'];
 const filtered=lots.filter(l=>Object.entries(filters).every(([k,v])=>!v||(k==='query'?JSON.stringify(l).toLowerCase().includes(v.toLowerCase()):k==='project'?data.plan.orders.some(o=>o.projectId===v&&o.allocations.some(a=>a.lotId===l.id)):k==='order'?data.plan.orders.some(o=>o.id===v&&o.allocations.some(a=>a.lotId===l.id)):l[k]===v)));
 return `<div class="flow">${stages.map(t=>`<div class="stage">${t}<strong>${lots.filter(l=>l.stage===t).length}</strong><small>个批次</small></div>`).join('')}</div><section class="panel"><div class="panel-head"><h2>跨厂批次台账</h2>${badge('数量单位独立保存')}</div><div class="filters"><input id="search" placeholder="查批次、Die、工单或负责人" value="${esc(filters.query)}"><label>工厂 <select data-filter="factory">${options(lots.map(l=>l.factory),filters.factory)}</select></label><label>工序 <select data-filter="stage">${options(lots.map(l=>l.stage),filters.stage)}</select></label><label>PN <select data-filter="pn">${options(lots.map(l=>l.pn),filters.pn)}</select></label><label>项目 <select data-filter="project">${options(data.state.projects.map(p=>p.id),filters.project)}</select></label><label>订单 <select data-filter="order">${options(data.state.orders.map(o=>o.id),filters.order)}</select></label></div>${table(['批次 / 完整 PN','工厂 / 工序','原始数量','预计良品 / 已分配','系统交期区间','质量 / 状态','最新源时间'],filtered.map(l=>`<tr><td>${button(esc(l.id),'lot',`class="link" data-id="${esc(l.id)}"`)}<small>${esc(l.pn||`共享 Die · ${l.die}`)}</small></td><td>${esc(l.factory)}<small>${esc(l.stage)}</small></td><td class="num">${n(l.quantity)} ${esc(l.unit)}</td><td class="num">${l.expected===null?'待确认':n(l.expected)}<small>已分配 ${n(l.allocated)}</small></td><td>${esc(l.eta.earliest||'待确认')}<small>至 ${esc(l.eta.latest||'待确认')}</small></td><td>${badge(l.quality==='released'?'已放行':l.quality==='hold'?'冻结':'待放行',l.quality==='hold'?'bad':l.quality==='released'?'good':'warn')}<small>${esc(l.status)}</small></td><td>${time(l.observedAt)}</td></tr>`))}${!filtered.length?'<div class="empty">没有符合条件的批次，试试调整筛选。</div>':''}</section>`;
}
function orders(){return `<section class="panel"><div class="panel-head"><h2>订单交付责任</h2>${badge('库存与在制分别呈现')}</div>${table(['客户 / 项目','订单行 / 客户 PO','PN','订单 / 已发','未交','现货覆盖','在制到期预计','到期缺口'],data.plan.orders.map(o=>`<tr><td>${esc(name('customers',o.customerId))}<small>${esc(name('projects',o.projectId))}</small></td><td>${button(esc(o.id),'order',`class="link" data-id="${o.id}"`)}<small>${esc(o.customerPo)}</small></td><td>${esc(o.pn)}<small>要求 ${o.due}</small></td><td class="num">${n(o.quantity)}<small>已发 ${n(o.shipped)}</small></td><td class="num">${n(o.open)}</td><td class="num">${n(o.stock)}</td><td class="num">${n(o.expected)}</td><td class="num">${badge(n(o.gap),o.gap?'bad':'good')}</td></tr>`))}</section><section class="panel"><h2>预测冲减：同一客户 × 项目 × PN × 月份</h2>${table(['预测版本','客户 / 项目','PN','预测数量','订单冲减','剩余预测'],data.plan.forecasts.map(f=>`<tr><td>${esc(f.id)} v${f.version}</td><td>${esc(name('customers',f.customerId))}<small>${esc(name('projects',f.projectId))}</small></td><td>${esc(f.pn)}</td><td class="num">${n(f.quantity)}</td><td class="num">${n(f.consumed)}</td><td class="num">${n(f.remaining)}</td></tr>`))}<p class="note">未来待覆盖 = 订单未交余额 + 剩余预测。当前 ${n(data.plan.futureDemand)} 颗。订单已发数量只扣未交，不再次扣预测；出货记录不代表收入确认。</p></section>`;}
function issues(){return `<section class="panel"><h2>异常与复核台账</h2>${table(['事项','影响对象','负责人','状态 / 下次复核','最新反馈','操作'],data.state.issues.map(x=>`<tr><td>${badge(x.kind,x.status==='resolved'?'good':'warn')}<small>${esc(x.reason)}</small></td><td>${esc(x.subject)}</td><td>${esc(x.owner)}</td><td>${esc({open:'待处理',following:'跟进中',resolved:'证据已消除异常'}[x.status])}<small>${time(x.nextCheck)}</small></td><td>${esc(x.notes.at(-1)?.note||'暂无人工反馈')}</td><td>${button('记录跟进','issue',`data-id="${x.id}"`)}</td></tr>`))}</section><section class="panel"><h2>有证据的调整建议</h2>${data.state.recommendations.map(x=>`<div class="row-card"><strong>${esc(x.orderId||x.kind)}</strong><p>${esc(x.text)}</p><small>${esc(x.status)}</small></div>`).join('')}</section>`;}
function production(){return `<div class="grid"><section class="panel"><h2>回货与交付</h2><p class="muted">回货需登记实际良品并确认放行；完成后再按订单出货。</p>${activeLots().filter(l=>l.pn&&l.quality!=='hold'&&l.status!=='paused').map(l=>`<div class="row-card"><div class="top"><strong>${esc(l.id)}</strong>${badge(l.stage)}</div><p>${esc(l.pn)} · ${n(l.quantity)} ${esc(l.unit)}</p>${l.stage==='成品库存'?button('登记模拟出货','ship',`data-id="${l.id}"`):['成品测试','质量放行'].includes(l.stage)?button('登记模拟回货','receipt',`data-id="${l.id}"`):badge('尚未到回货站点')} ${button('查看批次','lot',`data-id="${l.id}"`)}</div>`).join('')}</section><section><div class="panel"><h2>共享 Die 投料</h2><p class="muted">同一 Die 池按完整 PN 分流，提交后扣减源物料，创建独立加工批次。</p>${button('选择 PN 并模拟投料','release')}<h3 style="margin-top:24px">采购 / 加工 PO</h3>${table(['供应方','加工 PO / 工单','数量'],data.state.purchaseOrders.slice(-8).map(x=>`<tr><td>${esc(x.supplier)}</td><td>${esc(x.id)}<small>${esc(x.workOrderId)}</small></td><td>${n(x.quantity)} ${x.unit}</td></tr>`))}</div><div class="panel"><h2>出货与签收</h2>${data.state.shipments.map(x=>`<div class="row-card"><strong>${x.id} · ${n(x.quantity)} 颗</strong><small>${x.orderId} · ${x.source} · ${x.status}</small>${x.status==='在途'?button('模拟客户签收','delivered',`data-id="${x.id}"`):''}</div>`).join('')||'<p class="muted">暂无出货；原厂出货与客户签收分开记录。</p>'}</div></section></div>`;}
function agent(){return `<section class="panel"><h2>运营问答与工具证据</h2><form data-form="ask"><label>询问订单、批次或异常<input name="question" style="width:100%" placeholder="FT-01 延期影响哪些订单？" required maxlength="1000"></label><button class="primary">查询当前台账</button></form><div id="answer"></div><p class="muted">未配置语义服务时使用明确标注的关键词演示路由，未知问题不编造结论。</p>${(data.state.agentReviews||[]).map(r=>`<div class="row-card"><p>${esc(r.text)}</p><small>${esc(r.status)} · 引用 ${r.evidenceIds.map(esc).join('、')}</small></div>`).join('')}</section><section class="panel"><div class="panel-head"><h2>定时任务</h2>${badge('Asia/Shanghai')}</div><p class="note">这是可运行的规则执行器：读取多个 mock 来源、调用确定性计算、保存证据和待办。云端默认触发：每天09:00/15:00、周一09:30、每月5/20日10:00。下方修改业务规则后，如需精确改变云端唤醒时间，应同时调整站点定时任务。本地常驻调度器每分钟读取最新规则。未接入真实数据或外部消息通知。</p><p class="muted">最近调度心跳：${time(data.state.execution.lastTick)}</p>${data.state.schedules.map(s=>`<form class="row-card schedule" data-form="schedule" data-id="${s.id}"><div><strong>${esc(s.name)}</strong><small>${s.frequency==='daily'?'每天':s.frequency==='weekly'?'每周一':'每月两次'} · ${s.enabled?'已纳入调度规则':'已暂停'}</small></div><div class="controls"><input aria-label="小时" name="hour" type="number" min="0" max="23" value="${s.hour}" required>:<input aria-label="分钟" name="minute" type="number" min="0" max="59" value="${s.minute}" required>${s.days?`<input aria-label="第一个采购日期" name="day1" type="number" min="1" max="28" value="${s.days[0]}"> / <input aria-label="第二个采购日期" name="day2" type="number" min="1" max="28" value="${s.days[1]}">`:''}<label class="check"><input type="checkbox" name="enabled" ${s.enabled?'checked':''}>启用规则</label><button type="submit">保存</button></div></form>`).join('')}<div class="actions" style="margin-top:18px">${button('执行到期任务','tick')}${button('模拟下一次同步（+6小时）','advance')}${button('模拟来源冲突','conflict')}${button('模拟来源缺报','stale')}${button('重复上次同步键','repeat')}</div></section><section class="panel"><h2>运行记录</h2>${table(['运行时间','任务','结果','来源核对'],[...data.state.runs].reverse().slice(0,30).map(r=>`<tr><td>${time(r.time)}</td><td>${esc(r.kind)}<small>${esc(r.key)}</small></td><td>${badge(r.status,r.status==='succeeded'?'good':'warn')}</td><td>${r.outcomes.map(o=>`${esc(o.source)}：${o.error?esc(o.error):`${o.accepted||0} 接受 / ${o.rejected||0} 隔离`}`).join('<br>')}</td></tr>`))}</section><section class="panel"><h2>执行证据</h2><div class="timeline">${[...data.state.history].reverse().slice(0,25).map(x=>`<p><strong>${esc(x.kind)} · ${esc(x.subject)}</strong><small>${time(x.time)}</small>${esc(JSON.stringify(x.detail))}</p>`).join('')||'<p>点击立即同步开始产生运行证据。</p>'}</div></section>`;}
function dataPage(){return `<section class="panel"><h2>业务关联与数据边界</h2><p class="note">客户 → 项目 → 完整 PN → 预测 / 客户 PO → 销售订单行 → 数量分配 → 批次 / 库存 → 出货。共享 Die、加工 PO 和批次血缘是独立对象。</p>${table(['来源','内容','更新阈值','当前时间 / 版本'],data.state.sources.map(s=>`<tr><td>${esc(s.name)}</td><td>${s.format} mock 连接器</td><td>${s.maxAgeHours} 小时</td><td>${time(s.observedAt)}<small>v${s.version}</small></td></tr>`))}<h3 style="margin-top:24px">完整 PN 与共用 Die</h3>${table(['PN','Die','封装','路线'],data.state.parts.map(p=>`<tr><td>${p.id}</td><td>${p.die}</td><td>${p.package}</td><td>${p.routeId}</td></tr>`))}<h3 style="margin-top:24px">代理商授权与备货假设</h3>${table(['代理商','授权客户','mock 库存月数'],data.state.dealers.map(d=>`<tr><td>${esc(d.name)}</td><td>${d.customers.map(id=>esc(name('customers',id))).join('、')}</td><td>${d.stockMonths}</td></tr>`))}<p class="muted">备货月数为展示假设，不参与本轮交期计算，未冒充历史画像模型。</p></section><section class="panel"><h2>未归因 / 冲突隔离</h2>${data.state.quarantine.length?data.state.quarantine.map(q=>`<details><summary>${esc(q.entityId)} · ${esc(q.reason)}</summary><pre>${esc(JSON.stringify(q.raw,null,2))}</pre></details>`).join(''):'<p class="muted">暂无隔离记录。可在运行中心模拟来源冲突。</p>'}</section><section class="panel"><h2>批次血缘与物料转换</h2>${table(['事件','来源批次','目标批次','数量'],data.state.lineage.map(x=>`<tr><td>${x.kind}</td><td>${x.parents.join(', ')}</td><td>${x.children.join(', ')}</td><td>${n(x.quantity)} ${x.unit}</td></tr>`))}<details><summary>查看原始快照（可用于客户讨论）</summary><pre>${esc(JSON.stringify(data.state,null,2))}</pre></details></section>`;}
function render(){shell();$('#content').innerHTML=({today,wip,orders,issues,production,agent,data:dataPage}[view])();}
function modal(html){$('#detail-body').innerHTML=html;if(!$('#detail').open)$('#detail').showModal();}
function fields(items){return `<div class="detail-grid">${items.map(([k,v])=>`<div><span>${k}</span>${esc(v)}</div>`).join('')}</div>`;}
function lotDetail(id){const l=data.plan.lots.find(l=>l.id===id);const orders=data.plan.orders.filter(o=>o.allocations.some(a=>a.lotId===id));modal(`<h2>${esc(l.id)} · ${esc(l.stage)}</h2>${fields([['完整PN / Die',l.pn||l.die],['工厂 / 负责人',`${l.factory} / ${l.owner}`],['原始数量',`${n(l.quantity)} ${l.unit}`],['冻结 / 不可用',`${n(l.frozen)} / ${n(l.unusable)}`],['预计可用 / 已分配',`${n(l.expected)} / ${n(l.allocated)}`],['进入本站',time(l.enteredAt)],['本站停留',`${Math.max(0,Math.floor((Date.parse(data.state.clock)-Date.parse(l.enteredAt))/3600000))} 小时`],['最新源时间',time(l.observedAt)],['工厂承诺',`${l.promisedDate} / ${l.promiseConfirmed?'已确认':'待确认'}`],['系统估计',`${l.eta.earliest||'未知'} 至 ${l.eta.latest||'未知'}`]])}<h3>剩余路线</h3>${table(['步骤','排队工作日','加工/放行/物流工作日','档期'],l.remainingRoute.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.queue?.join('–')||'未知'}</td><td>${r.duration?.join('–')||'未知'}</td><td>${r.confirmedStart||'待确认'}</td></tr>`))}<p class="note">${l.eta.conditions.map(esc).join('；')||'成品已放行，仍需按订单安排发运。'}</p><h3>关联订单与客户项目</h3>${orders.map(o=>`<p>${esc(o.id)} · ${esc(name('customers',o.customerId))} / ${esc(name('projects',o.projectId))} · 分配 ${n(o.allocations.find(a=>a.lotId===id).quantity)} 颗</p>`).join('')||'<p>尚未分配，共享 Die 需先指定完整 PN 与路线。</p>'}<details><summary>来源证据</summary><pre>${esc(JSON.stringify({sourceId:l.sourceId,sourceRecord:l.sourceRecord,workOrderId:l.workOrderId,version:l.version,sourceTime:l.observedAt},null,2))}</pre></details><div class="actions">${button('暂停 / 恢复','pause',`data-id="${id}"`)}${button('拆分批次','split',`data-id="${id}"`)}${button('合并同类批次','merge',`data-id="${id}"`)}${button('登记返工','rework',`data-id="${id}"`)}${l.stage==='封装'?button('模拟封装完成转测试','transfer',`data-id="${id}"`):''}</div>`);}
function orderDetail(id){const o=data.plan.orders.find(o=>o.id===id);modal(`<h2>${id}</h2><p>${esc(name('customers',o.customerId))} / ${esc(name('projects',o.projectId))}</p>${fields([['完整PN',o.pn],['客户/代理商PO',o.customerPo],['未交余额',n(o.open)],['到期缺口',n(o.gap)]])}${table(['供给批次','分配数量','预计交期','是否覆盖要求日'],o.allocations.map(a=>`<tr><td>${a.lotId}</td><td>${n(a.quantity)}</td><td>${a.earliest||'未知'} 至 ${a.latest||'未知'}</td><td>${badge(a.onTime?'预计按期':'不能覆盖',a.onTime?'good':'bad')}</td></tr>`))}<p class="note">${o.allowPartial?`可分批：现货覆盖 ${n(o.stock)} 颗；在制到期预计 ${n(o.expected)} 颗。实际发货仍需放行、数量与物流确认。`:'该订单不允许分批交付。'}</p>`);}
$('#nav').onclick=e=>{const b=e.target.closest('[data-view]');if(b){view=b.dataset.view;render();}};
$('#sync').onclick=()=>run({type:'sync'});$('#reload').onclick=()=>load().catch(e=>notify(e.message,true));$('#close').onclick=()=>$('#detail').close();
document.addEventListener('change',e=>{if(e.target.dataset.filter){filters[e.target.dataset.filter]=e.target.value;render();}if(e.target.id==='search'){filters.query=e.target.value;render();}});
let lastSyncCommand,lastSyncKey;
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;
 if(['delay','conflict','stale'].includes(a)){lastSyncCommand={type:'sync',scenario:a};lastSyncKey=crypto.randomUUID();await run(lastSyncCommand,lastSyncKey);}
 if(a==='repeat'){if(lastSyncKey)await run(lastSyncCommand,lastSyncKey);else notify('先执行一次模拟来源同步，再重复其操作键。');}
 if(a==='lot')lotDetail(id);if(a==='order')orderDetail(id);if(a==='production'){view='production';render();}
 if(a==='tick')await run({type:'tick'});
 if(a==='advance'){await run({type:'advance',hours:6});await run({type:'tick'});}
 if(['pause','rework','transfer'].includes(a)){await run({type:a,lotId:id});$('#detail').close();}
 if(a==='delivered')await run({type:'delivered',shipmentId:id});
 if(a==='expedite'){const x=data.expedite;if(!x)return notify('批次已转出，演示加急方案不再适用。',true);modal(`<h2>加急方案：先看影响，再记录接受</h2><p class="note">${esc(x.constraint)}</p>${table(['订单 / 客户','调整前到期缺口','调整后到期缺口'],x.changes.map(o=>`<tr><td>${o.orderId}<small>${esc(name('customers',o.customerId))}</small></td><td>${n(o.beforeGap)}</td><td>${n(o.afterGap)}</td></tr>`))}<p>这里只登记 mock 工厂反馈，不发送请求、不修改真实排期。</p>${button('记录模拟工厂已接受','accept-expedite')}`);}
 if(a==='accept-expedite'){await run({type:'expedite',confirmed:true});$('#detail').close();}
 if(a==='issue'){const x=data.state.issues.find(x=>x.id===id);modal(`<h2>${esc(x.kind)} · ${esc(x.subject)}</h2><p>${esc(x.reason)}</p><p class="note">${esc(x.nextAction)}</p><form data-form="followup" data-id="${id}"><label>人工反馈<textarea name="note" required maxlength="1000"></textarea></label><label>下次复核时间<input name="nextCheck" type="datetime-local" required value="2026-10-02T09:00"></label><button class="primary">保存跟进</button></form>${x.notes.map(n=>`<p>${esc(n.note)}<small>${time(n.time)}</small></p>`).join('')}`);}
 if(a==='receipt'||a==='ship'){const l=data.plan.lots.find(l=>l.id===id);const choices=data.plan.orders.filter(o=>o.allocations.some(x=>x.lotId===id));modal(`<h2>${a==='receipt'?'登记实际回货（mock）':'登记出货（mock）'} · ${id}</h2><form data-form="${a}" data-id="${id}">${a==='ship'?`<label>对应销售订单<select name="orderId">${choices.map(o=>`<option value="${o.id}">${o.id} · ${name('customers',o.customerId)}</option>`).join('')}</select></label>`:''}<label>${a==='receipt'?'实测良品数量':'出货数量'}<input type="number" name="quantity" min="1" max="${l.quantity}" value="${l.quantity}" required></label>${a==='receipt'?'<label class="check"><input name="released" type="checkbox" required>已取得模拟质量放行记录</label>':''}<p class="muted">${a==='receipt'?'原批次关闭并转换为库存，避免重复供给。':'出货减少库存与订单未交；签收单独登记。'}</p><button class="primary" style="margin-top:15px">保存模拟记录</button></form>`);}
 if(a==='release'){modal(`<h2>共享 Die 投料（mock）</h2><form data-form="release"><label>源Die批次<select name="lotId">${activeLots().filter(l=>l.stage==='Die 库存').map(l=>`<option>${l.id}</option>`).join('')}</select></label><label>目标完整PN<select name="pn">${data.state.parts.map(p=>`<option>${p.id}</option>`).join('')}</select></label><label>投料Die数量<input type="number" name="quantity" min="1" value="10000" required></label><p class="note">系统验证Die兼容性，扣减共享池后创建独立加工批次。此操作仅模拟，不向工厂下单。</p><button class="primary">登记模拟投料</button></form>`);}
 if(a==='split')modal(`<h2>拆分 ${id}</h2><form data-form="split" data-id="${id}"><label>子批次编号<input name="childId" required pattern="[A-Za-z0-9-]+" value="${id}-S1"></label><label>拆出数量<input name="quantity" type="number" min="1" required></label><button>保存拆分</button></form>`);
 if(a==='merge')modal(`<h2>合并到 ${id}</h2><form data-form="merge" data-id="${id}"><label>来源批次<select name="other">${activeLots().filter(l=>l.id!==id).map(l=>`<option>${l.id}</option>`).join('')}</select></label><p class="muted">仅同PN、工序、工厂、质量、单位、分配与路线可合并。</p><button>核对并合并</button></form>`);
});
document.addEventListener('submit',async e=>{const f=e.target.closest('[data-form]');if(!f)return;e.preventDefault();const v=Object.fromEntries(new FormData(f));const type=f.dataset.form;let command={type};
 if(type==='ask'){try{const r=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:v.question})});const a=await r.json();if(!r.ok)throw Error(a.error);$('#answer').innerHTML=`<div class="row-card">${badge(a.mode)}<p>${esc(a.message)}</p><small>调用工具：${esc(a.tool)} · 快照 ${time(a.at)}</small><pre>${esc(JSON.stringify(a.evidence,null,2))}</pre></div>`;}catch(e){notify(e.message,true);}return;}

 if(type==='schedule')command={type,id:f.dataset.id,values:{hour:+v.hour,minute:+v.minute,enabled:!!v.enabled,days:[+v.day1,+v.day2]}};
 if(type==='followup')command={type,issueId:f.dataset.id,note:v.note,nextCheck:v.nextCheck+'+08:00'};
 if(type==='receipt'||type==='ship')command={type,lotId:f.dataset.id,quantity:+v.quantity,orderId:v.orderId,released:!!v.released};
 if(type==='release')command={type,lotId:v.lotId,pn:v.pn,quantity:+v.quantity};
 if(type==='split')command={type,lotId:f.dataset.id,childId:v.childId,quantity:+v.quantity};
 if(type==='merge')command={type,lotIds:[f.dataset.id,v.other]};
 const r=await run(command);if(r)$('#detail').close();
});
load().catch(e=>notify(`加载失败：${e.message}。可点击刷新重试。`,true));
