const E=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const N=v=>new Intl.NumberFormat('zh-CN').format(v??0);
const labels={new:'待分析',running:'分析中',review:'待人工决策',vendor:'待工厂确认',tracking:'执行跟踪',verify:'待结果核验',closed:'已关闭'};
let selectedCase,selectedLot,selectedPlan,mode='cards',mobile='wip',full=false,filter={customer:'',project:'',pn:'',factory:''};
const b=(label,action,id='',cls='')=>`<button class="${cls}" data-wb="${action}" data-id="${E(id)}">${label}</button>`;
const tag=(t,kind='')=>`<span class="tag ${kind}">${E(t)}</span>`;
const date=d=>d?d.slice(0,10):'待确认';
const T=d=>d?new Date(d).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—';
export function workbench(d,workspace){
 const s=d.state,a=s.aip,c=a.cases.find(c=>c.id===selectedCase)||a.cases.find(c=>c.status!=='closed')||a.cases[0];selectedCase=c?.id;
 const r=a.runs.find(r=>r.id===c?.runIds.at(-1)),proposal=r?.plans.find(p=>p.id===selectedPlan),order=d.plan.orders.find(o=>o.id===c?.orderId);
 const highlights=new Set([...(proposal?.lotIds||c?.lotIds||[]),selectedLot].filter(Boolean));
 const lots=d.plan.lots.filter(l=>!['closed','shipped'].includes(l.status)).filter(l=>(!filter.pn||l.pn===filter.pn)&&(!filter.factory||l.factory===filter.factory)&&d.plan.orders.some(o=>(!filter.customer||o.customerId===filter.customer)&&(!filter.project||o.projectId===filter.project)&&(o.allocations.some(x=>x.lotId===l.id)||(!filter.customer&&!filter.project))));
 const field=(key,title,items)=>`<label>${title}<select data-wb-filter="${key}"><option value="">全部</option>${items.map(([id,label])=>`<option value="${E(id)}" ${filter[key]===id?'selected':''}>${E(label)}</option>`).join('')}</select></label>`;
 const controls=`<div class="wb-toolbar"><div class="wb-filters">${field('customer','客户',s.customers.map(x=>[x.id,x.name]))}${field('project','项目',s.projects.map(x=>[x.id,x.name]))}${field('pn','完整 PN',s.parts.map(x=>[x.id,x.id]))}${field('factory','工厂',[...new Set(s.lots.map(x=>x.factory))].map(x=>[x,x]))}</div><div class="wb-actions">${tag(workspace==='demo'?'共享台账':'独立演示空间','cyan')}${workspace!=='demo'?b('回到共享台账','shared'):''}${b('新建正常场景','new')}${b('模拟测试延期','delay','','danger')}</div></div>`;
 const kpis=`<div class="wb-kpis">${[['交付风险订单',d.plan.orders.filter(o=>o.gap>0).length,'按要求日计算','red'],['待人工决策',a.cases.filter(c=>c.status==='review').length,'方案审核与证据补充','purple'],['待工厂确认',a.cases.filter(c=>c.status==='vendor').length,'内部批准 ≠ 工厂接受','amber'],['今日预计回货',d.plan.lots.filter(l=>l.stage!=='成品库存'&&!['closed','shipped'].includes(l.status)&&l.eta.latest===date(s.clock)).length,'批次 · 待实际放行','green']].map(([label,value,note,color])=>`<div class="wb-kpi ${color}"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`).join('')}</div>`;
 const card=l=>`<article class="lot-card ${highlights.has(l.id)?'selected':''}" data-wb="select-lot" data-id="${E(l.id)}" tabindex="0" role="button"><div class="card-top"><strong>${E(l.id)}</strong>${tag(l.quality==='hold'?'冻结':l.status==='rework'?'返工':l.quality==='released'?'已放行':'在制',l.quality==='hold'?'red':'cyan')}</div><div class="pn">${E(l.pn||'共享 Die · '+l.die)}</div><div class="lot-qty">${N(l.quantity)} <small>${E(l.unit)}</small></div><div class="card-meta">${E(l.factory)}<br>预计 ${date(l.eta.earliest)} ～ ${date(l.eta.latest)}<br>承诺 ${date(l.promisedDate)} · ${l.promiseConfirmed?'已确认':'待确认'}</div>${s.issues.filter(x=>x.status!=='resolved'&&x.subject===l.id).map(x=>tag(x.kind,'amber')).join('')}<div class="card-footer">${b('批次详情','detail-lot',l.id)}${b('关联事项','lot-case',l.id)}</div></article>`;
 const columns=['晶圆制造','晶圆测试','Die 库存','封装','成品测试','质量放行','成品库存'];
 const board=`<div class="wip-alert">${b('查看 '+(c?.orderId||'订单')+' 关联批次','focus-case')}${tag('当前缺口 '+N(order?.gap)+' 颗','amber')}</div><div class="stage-nav">${columns.map((stage,i)=>b(stage,'stage',String(i))).join('')}</div><div class="wip-board">${columns.map((stage,i)=>`<section class="wip-column"><div class="column-title"><span><small>0${i+1}</small> ${stage}</span><b>${lots.filter(l=>l.stage===stage).length}</b></div>${lots.filter(l=>l.stage===stage).map(card).join('')||'<p class="no-lots">暂无批次</p>'}</section>`).join('')}</div>`;
 const ledger=`<div class="table-wrap"><table><thead><tr><th>批次 / PN</th><th>工厂 / 工序</th><th>数量</th><th>预计回货</th><th>操作</th></tr></thead><tbody>${lots.map(l=>`<tr class="${highlights.has(l.id)?'linked':''}"><td>${E(l.id)}<small>${E(l.pn||l.die)}</small></td><td>${E(l.factory)}<small>${E(l.stage)}</small></td><td>${N(l.quantity)} ${l.unit}</td><td>${date(l.eta.latest)}</td><td>${b('查看','detail-lot',l.id)}</td></tr>`).join('')}</tbody></table></div>`;
 function timeline(){const origin=Date.parse(date(s.clock)),days=21;const pos=t=>Math.max(0,Math.min(100,(Date.parse(t)-origin)/86400000/days*100));return `<div class="schedule-legend">${tag('当前估计','cyan')}${tag('建议计划','purple')}${tag('工厂确认','green')}<span>回货节点 · 按日 · 未确认档期不等于可执行产能</span></div><div class="schedule-days"><span>工厂 / 批次</span><div>${Array.from({length:7},(_,i)=>`<span>${new Date(origin+i*3*86400000).toISOString().slice(5,10)}</span>`).join('')}</div></div>${lots.filter(l=>l.stage!=='成品库存').map(l=>{const patch=proposal?.patches.find(x=>x.id===l.id);return `<div class="schedule-row"><div><strong>${E(l.id)}</strong><small>${E(l.factory)} / ${E(l.stage)}</small></div><div class="tracks">${[['current',l.eta.latest,'估计'],['proposed',patch?.promisedDate,'建议'],['confirmed',l.promiseConfirmed?l.promisedDate:null,'确认']].map(([cl,t,label])=>`<div class="track">${t?`<span class="marker ${cl}" style="left:clamp(0px,${pos(t)}%,calc(100% - 95px))">${label} ${t.slice(5)}</span>`:`<small>${label}：待确认</small>`}</div>`).join('')}</div></div>`;}).join('')}`;}
 const left=`<section class="wb-surface wip-surface"><div class="surface-title"><div><span class="section-code">01 / PRODUCTION</span><h2>全链路 WIP</h2></div><div class="segmented">${[['cards','批次看板'],['table','台账'],['timeline','工厂排期']].map(([id,t])=>b(t,'mode',id,mode===id?'active':'')).join('')}</div></div>${mode==='cards'?board:mode==='table'?ledger:timeline()}<div class="surface-foot">${lots.length} 个活跃批次 · 数量单位独立核算 · 选中方案后高亮受影响批次</div></section>`;
 const flow=`<div class="aip-flow">${Object.entries(labels).map(([state,label])=>`<section class="aip-column"><div class="column-title">${label} <b>${a.cases.filter(c=>c.status===state).length}</b></div>${a.cases.filter(c=>c.status===state).map(x=>`<button class="case-card ${c?.id===x.id?'selected':''}" data-wb="case" data-id="${x.id}"><strong>${E(x.orderId)}</strong><span>${E(x.title)}</span><small>${E(x.owner)} · 缺口 ${N(x.currentGap)} 颗</small>${x.overdue?tag('待复核','amber'):''}</button>`).join('')||'<p class="no-lots">暂无事项</p>'}</section>`).join('')}</div>`;
 const request=a.requests.find(q=>q.id===c?.requestId);
 function panel(){if(!c)return '<p class="empty">暂无处理事项</p>';return `<div class="case-header"><div class="case-select"><select data-wb-case>${a.cases.map(x=>`<option value="${x.id}" ${x.id===c.id?'selected':''}>${E(x.orderId)} · ${labels[x.status]}</option>`).join('')}</select>${tag(labels[c.status],'purple')}</div><h3>${E(s.customers.find(x=>x.id===order?.customerId)?.name)} · ${E(s.projects.find(x=>x.id===order?.projectId)?.name)}</h3><p>${E(order?.pn)}<br>目标：核实供给与交期，降低 ${N(order?.gap)} 颗到期缺口</p><div class="case-meta">${E(c.owner)} · ${c.id}<br>下次复核 ${T(c.nextCheck)} ${c.overdue?'· 已到复核时间':''}</div></div>
 <div class="aip-section"><div class="section-heading"><h3>执行过程</h3>${tag('模拟编排','purple')}</div>${!r?'<p class="muted">就地读取关联订单、批次和来源，形成可审核方案。</p>':''}${r?.steps.map(step=>`<details class="step ${step.status}"><summary><span>${step.status==='succeeded'?'✓':'!'} ${E(step.name)}</span><small>${step.status==='succeeded'?`${step.durationMs} ms`:'失败'}</small></summary><p>${E(step.tool)} · ${T(step.at)}</p><pre>${E(JSON.stringify(step.output||{error:step.error},null,2))}</pre></details>`).join('')||''}${c.error?`<div class="wb-warning">${E(c.error)}</div>`:''}<div class="wb-actions">${['new','review','verify','vendor'].includes(c.status)?b(r?'重新分析':'启动 Agent 分析','start',c.id,'primary'):''}${c.status==='running'?b('继续执行下一步','step',c.id,'primary')+b('自动运行至审核','auto',c.id)+b('模拟工具失败','fail',c.id):''}</div></div>
 ${r?.plans.length?`<div class="aip-section"><h3>方案与影响</h3>${r.plans.map(p=>`<article class="proposal ${selectedPlan===p.id?'selected':''}"><div class="card-top">${b(E(p.name),'plan',p.id,p.available?'':'muted')}${tag(p.available?'可审核':'待核实',p.available?'purple':'amber')}</div><p>${E(p.condition)}</p>${p.changes.filter(x=>x.orderId===c.orderId||x.beforeGap!==x.afterGap).map(x=>`<div class="delta"><span>${E(x.orderId)}</span><strong class="${x.afterGap>x.beforeGap?'red':'green'}">${N(x.beforeGap)} → ${N(x.afterGap)}<small> 颗缺口</small></strong></div>`).join('')}<small>费用：待补充</small>${c.status==='review'&&p.available?b('选择并审核','approve',p.id):''}</article>`).join('')}</div>`:''}
 ${request?`<div class="aip-section"><h3>审核与工厂反馈</h3><p>${E(request.plan.name)} · ${E({approved:'内部已批准，尚未提交',submitted:'已模拟提交，待工厂回复',accepted:'工厂已接受',rejected:'工厂已拒绝',partial:'工厂提出替代日期'}[request.status])}</p><small>审核理由：${E(c.approval?.reason)}</small><div class="wb-actions">${request.status==='approved'&&c.status==='vendor'?b('模拟提交请求','submit',c.id,'primary'):''}${request.status==='submitted'&&c.status==='vendor'?b('登记工厂反馈','reply',c.id,'primary'):''}${['vendor','tracking','verify'].includes(c.status)?b('复核最新结果','recheck',c.id):''}</div></div>`:''}
 ${['tracking','verify'].includes(c.status)?`<div class="aip-section"><h3>执行与实际结果</h3><p>工厂接受后，继续跟进回货、质量放行与实际出货。</p><div class="wb-actions">${c.lotIds.filter(id=>s.lots.some(l=>l.id===id&&l.stage==='成品测试'&&l.status==='active')).map(id=>b('回货 '+id,'receipt',id)).join('')}${d.plan.orders.find(o=>o.id===c.orderId)?.allocations.filter(x=>x.firm).map(x=>b('出货 '+x.lotId,'ship',x.lotId)).join('')}</div>${c.verification?`<div class="result-grid"><div>预计转回<strong>${N(c.verification.expected)}</strong></div><div>实际良品<strong>${N(c.verification.actual)}</strong></div><div>仍存缺口<strong>${N(c.verification.gap)}</strong></div></div><small>核验时间 ${T(c.verification.at)} · 差异 ${N(c.verification.actual-c.verification.expected)} 颗</small>${c.status==='verify'?b('核验结案 / 交接余量','close',c.id):''}`:''}</div>`:''}
 <div class="aip-section"><details><summary>处理履历与证据快照</summary>${c.history.map(x=>`<p><small>${T(x.time)}</small><br>${E(x.text)}</p>`).join('')}${r?`<details><summary>分析输入快照 ${r.id}</summary><pre>${E(JSON.stringify(r.snapshot,null,2))}</pre></details>`:''}</details></div>`;}
 const right=`<aside class="wb-surface aip-surface"><div class="surface-title"><div><span class="section-code purple">02 / AGENT IN PROCESS</span><h2>AIP 处理工作区</h2></div>${b(full?'返回同屏':'流程全屏','full')}</div>${panel()}</aside>`;
 const affectedOrders=d.plan.orders.filter(o=>o.id===c?.orderId||proposal?.changes.some(x=>x.orderId===o.id&&x.beforeGap!==x.afterGap)||o.allocations.some(x=>x.lotId===selectedLot));
 const bottom=`<section class="wb-surface linked-orders"><div class="surface-title"><h2>关联订单与交付责任</h2>${tag('原厂出货 ≠ 客户销量 ≠ 收入')}</div><div class="table-wrap"><table><thead><tr><th>客户 / 项目</th><th>订单 / 完整 PN</th><th>要求交期</th><th>未交</th><th>现货</th><th>到期在制</th><th>缺口</th></tr></thead><tbody>${affectedOrders.map(o=>`<tr><td>${E(s.customers.find(x=>x.id===o.customerId)?.name)}<small>${E(s.projects.find(x=>x.id===o.projectId)?.name)}</small></td><td>${b(o.id,'detail-order',o.id)}<small>${E(o.pn)}</small></td><td>${o.due}</td><td>${N(o.open)}</td><td>${N(o.stock)}</td><td>${N(o.expected)}</td><td class="red">${N(o.gap)}</td></tr>`).join('')}</tbody></table></div></section>`;
 return `<div class="workbench ${full?'full-flow':''} mobile-${mobile}">${controls}${kpis}<div class="mobile-tabs">${b('WIP 生产','mobile','wip',mobile==='wip'?'active':'')}${b('AIP 处理','mobile','aip',mobile==='aip'?'active':'')}</div>${full?flow:''}<div class="wb-layout">${left}${right}</div>${bottom}</div>`;
}
export function connectWorkbench(ctx){
 const current=()=>{const d=ctx.data();return d.state.aip.cases.find(c=>c.id===selectedCase);};
 const command=async(type,extra={})=>ctx.run({type,caseId:current()?.id,...extra});
 const analyse=async()=>{if(await command('aip_start'))await step();};
 const step=async(failure=false)=>{const c=current(),r=ctx.data().state.aip.runs.find(r=>r.id===c.runIds.at(-1));await command('aip_step',{index:r.steps.filter(x=>x.status==='succeeded').length,...(failure?{simulateFailure:true}:{})});};
 document.addEventListener('change',e=>{if(e.target.dataset.wbFilter){filter[e.target.dataset.wbFilter]=e.target.value;ctx.render();}if(e.target.matches('[data-wb-case]')){selectedCase=e.target.value;selectedPlan=null;ctx.render();}});
 document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.lot-card')){e.preventDefault();e.target.click();}});
 document.addEventListener('click',async e=>{const el=e.target.closest('[data-wb]');if(!el)return;const action=el.dataset.wb,id=el.dataset.id;
 if(action==='stage'){const board=document.querySelector('.wip-board');board.scrollTo({left:Number(id)*230,behavior:'smooth'});return;}
 if(action==='focus-case'){const board=document.querySelector('.wip-board'),card=board?.querySelector('.lot-card.selected');if(board&&card)board.scrollTo({left:card.offsetLeft-board.offsetLeft-16,behavior:'smooth'});return;}
 if(action==='mode')mode=id;if(action==='mobile')mobile=id;if(action==='full')full=!full;if(action==='plan')selectedPlan=id;
 if(action==='case'){selectedCase=id;selectedPlan=null;mobile='aip';}
 if(action==='select-lot')selectedLot=id;
 if(action==='lot-case'){const c=ctx.data().state.aip.cases.find(c=>c.lotIds.includes(id)&&c.status!=='closed');if(c){selectedCase=c.id;mobile='aip';}else ctx.notice('该批次暂无交付缺口事项，可查看详情及异常台账。');}
 if(['mode','mobile','full','plan','case','select-lot','lot-case'].includes(action)){ctx.render();return;}
 if(action==='shared'){selectedCase=null;selectedPlan=null;await ctx.shared();return;}
 if(action==='new'){selectedCase=null;selectedPlan=null;await ctx.newSpace();return;}
 if(action==='delay'){await ctx.run({type:'sync',scenario:'delay'});return;}
 if(action==='detail-lot')ctx.lot(id);if(action==='detail-order')ctx.order(id);
 if(action==='receipt'||action==='ship'){document.dispatchEvent(new CustomEvent('wb-business',{detail:{action,id}}));return;}
 if(action==='auto'){const startCase=selectedCase;for(let i=0;i<4;i++){if(selectedCase!==startCase||current()?.status!=='running')break;const before=ctx.data().revision;await step();if(ctx.data().revision===before)break;}return;}
 if(action==='start')await analyse();if(action==='step')await step();if(action==='fail')await step(true);if(action==='submit')await command('aip_submit');if(action==='recheck')await command('aip_recheck');
 if(action==='approve')ctx.modal(`<h2>审核方案</h2><p>同时核对被挤占订单；批准后还需工厂确认。</p><form data-wb-form="approve" data-plan="${E(id)}"><label>审核理由<textarea name="reason" required maxlength="1000"></textarea></label><button class="primary">批准并保留记录</button></form>`);
 if(action==='reply')ctx.modal(`<h2>登记工厂回复（mock）</h2><form data-wb-form="reply"><label>反馈<select name="reply"><option value="accepted">接受</option><option value="rejected">拒绝</option><option value="partial">部分接受：提出替代回货日期</option></select></label><label>替代日期（部分接受时填写）<input type="date" name="date" value="2026-10-09"></label><label>工厂反馈依据<textarea name="note" required maxlength="1000"></textarea></label><button class="primary">保存模拟反馈</button></form>`);
 if(action==='close')ctx.modal(`<h2>核验结案</h2><p>结案记录实际差异；剩余缺口会生成新的协调事项继续跟踪。</p><form data-wb-form="close"><label>核验结论与交接说明<textarea name="reason" required maxlength="1000"></textarea></label><button class="primary">确认核验并交接</button></form>`);
 });
 document.addEventListener('submit',async e=>{const f=e.target.closest('[data-wb-form]');if(!f)return;e.preventDefault();const v=Object.fromEntries(new FormData(f));const type=f.dataset.wbForm;const result=await command({approve:'aip_approve',reply:'aip_reply',close:'aip_close'}[type],{...v,...(type==='approve'?{planId:f.dataset.plan}:{})});if(result)document.querySelector('#detail').close();});
}
